// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dofidfrfuouiifevygkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZmlkZnJmdW91aWlmZXZ5Z2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjUxMzgsImV4cCI6MjA3MTkwMTEzOH0.h8DKMkQSD0MCtRirzYhP2JZA8cmsa59Y1Ww5q3qTF24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});